project:
  type: website

website:
  title: "NCA Analysis Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Scripts/admiral-pharmaverse.qmd
        text: CDISCPILOT NCA
      - href: Scripts/ADNCA-dataprep.qmd
        text: DAPA01 NCA
      - href: Scripts/admiral-summarytables.qmd
        text: Summary Tables

format:
  html:
    theme: cosmo
    toc: true




