project:
  type: website
  output-dir: docs

website:
  title: "NCA Analysis Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/mshas7/quarto_project
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true




